name: hola_mundo

on:
  push:
    branches:
      - "main"

jobs:

  hola_mundo:
    runs-on: ubuntu-latest
    steps:
      - name: imprimir
        run: echo "hola mundo"
      - name: clonar repo
        run: git clone https://${{github.actor}}:${{github.token}}@github.com/sebitas0623/workshop_gitAction.git